import type { Work } from "@/shared/types";

const LOREM =
  "Lorem ipsum dolor sit amet consectetur. Aenean ut magna justo libero risus neque at felis donec. Sit pulvinar cursus tempus ullamcorper facilisis elementum id velit convallis. Ac nulla suspendisse velit sit mattis vulputate aenean. Nunc in pretium in velit enim ut pulvinar dis. Est viverra mattis id sed neque erat vulputate duis.";

const twoParas = `${LOREM}\n\n${LOREM}`;

const gallery7 = (a: string, b: string, c: string): string[] => [a, b, c, a, b, c, a];

export const works: Work[] = [
  {
    slug: "mh-padel-club",
    title: "MH Padel Club",
    category: "Website",
    year: 2024,
    description: "Full-stack website for a padel sports club with booking system and brand identity.",
    tags: ["Web Design", "FULL STACK DEVELOPMENT", "Brand Design"],
    image: "/backgrounImage.png",
    featured: true,
    client: "John Doe",
    date: "05 Mar 2026",
    services: [
      "Logo Design",
      "Web Design",
      "UI / UX Design",
      "Marketing",
      "Full Stack Development",
      "Illustrations",
    ],
    about: "MH Padel is one of the largest and most advanced padel clubs in Riga, featuring multiple courts, a sauna, and a full relaxation area. The goal was to create a digital platform that reflects the premium experience of the club and simplifies user interaction across all devices. \b \b  We designed and developed a complete digital platform, including UI/UX design and full-stack development. The project included a custom CRM system, an admin panel for operations, and a membership system with booking functionality. We also created copywriting and content structure, ensuring a clear experience across all devices.",
    gallery: gallery7("/backgrounImage.png", "/topimage.jpg", "/bottomimage.jpg"),
    approach: "The interface was built with a strong focus on usability, motion, and clear navigation. Smooth animations and structured user flows guide visitors naturally through the platform, making it easy to explore services, manage bookings, and interact with the system without friction.Through content, imagery, and structure, we built a digital experience that captures the energy of the club. From the first screen, users feel the atmosphere and are naturally guided to book a court, join as members, and become part of the club.",
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "mobi-scambank",
    title: "Mobi Scambank",
    category: "Marketing",
    year: 2024,
    description: "Marketing campaign and digital presence for a fintech startup.",
    tags: ["Marketing", "Branding"],
    image: "/topimage.jpg",
    featured: true,
    client: "Alex Carter",
    date: "12 Jan 2026",
    services: ["Branding", "Marketing", "Social Media", "Web Design"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/bottomimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "gpu-service",
    title: "GPU Service",
    category: "Turnkey Website",
    year: 2024,
    description: "Turnkey e-commerce website for a GPU repair and sales service.",
    tags: ["Website", "E-commerce"],
    image: "/bottomimage.jpg",
    featured: true,
    client: "Mike Stevens",
    date: "20 Feb 2026",
    services: ["Web Design", "E-commerce", "Full Stack Development"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/backgrounImage.png", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "interface-studio",
    title: "Interface Studio",
    category: "Interface",
    year: 2024,
    description: "Product design system for a SaaS startup with complex multi-role dashboard.",
    tags: ["Interface", "UI/UX", "Design System"],
    image: "/topimage.jpg",
    featured: true,
    client: "Daniel Frost",
    date: "18 Jan 2026",
    services: ["UI / UX Design", "Interface Design", "Design System", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "nova-brand",
    title: "Nova Brand",
    category: "Branding",
    year: 2024,
    description: "Brand identity and visual language for a luxury lifestyle label.",
    tags: ["Branding", "Logo & Identity"],
    image: "/bottomimage.jpg",
    featured: true,
    client: "Sara Bell",
    date: "02 Mar 2026",
    services: ["Logo Design", "Branding", "Visual Identity", "Typography"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "flow-app",
    title: "Flow App",
    category: "Application",
    year: 2024,
    description: "Mobile productivity app with focus on calm UX and habit tracking.",
    tags: ["Application", "Mobile", "UI/UX"],
    image: "/backgrounImage.png",
    featured: true,
    client: "Leo Grant",
    date: "25 Feb 2026",
    services: ["Mobile Design", "UI / UX Design", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "brand-identity-co",
    title: "Brand Identity Co.",
    category: "Branding",
    year: 2023,
    description: "Complete brand identity system for a design consultancy.",
    tags: ["Branding", "Logo & Identity"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Sophie Lane",
    date: "08 Nov 2025",
    services: ["Logo Design", "Branding", "Visual Identity", "Typography"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "interface-lab",
    title: "Interface Lab",
    category: "Interface",
    year: 2023,
    description: "UI/UX design for a SaaS dashboard with complex data visualisation.",
    tags: ["Interface", "UI/UX"],
    image: "/topimage.jpg",
    featured: false,
    client: "David Kim",
    date: "15 Oct 2025",
    services: ["UI / UX Design", "Interface Design", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "sport-app",
    title: "Sport App",
    category: "Application",
    year: 2023,
    description: "Mobile application for sports event management and team coordination.",
    tags: ["Application", "Mobile"],
    image: "/backgrounImage.png",
    featured: false,
    client: "James Walker",
    date: "03 Sep 2025",
    services: ["Mobile Design", "UI / UX Design", "App Development"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "logo-studio",
    title: "Logo Studio",
    category: "Logo & Identity",
    year: 2023,
    description: "Logomark and identity system for a creative studio.",
    tags: ["Logo & Identity", "Branding"],
    image: "/topimage.jpg",
    featured: false,
    client: "Emma Ross",
    date: "22 Jul 2025",
    services: ["Logo Design", "Brand Identity", "Illustrations"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "graphic-press",
    title: "Graphic Press",
    category: "Graphic Design",
    year: 2023,
    description: "Editorial and print design for an independent magazine.",
    tags: ["Graphic Design", "Print"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Nina Black",
    date: "30 Jun 2025",
    services: ["Graphic Design", "Editorial Design", "Print"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/backgrounImage.png", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "turnkey-shop",
    title: "Turnkey Shop",
    category: "Turnkey Website",
    year: 2022,
    description: "Ready-to-launch e-commerce solution for a fashion retailer.",
    tags: ["Turnkey Website", "E-commerce"],
    image: "/backgrounImage.png",
    featured: false,
    client: "Chris Ford",
    date: "18 May 2025",
    services: ["Web Design", "E-commerce", "Full Stack Development"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/topimage.jpg", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "padel-arena",
    title: "Padel Arena",
    category: "Website",
    year: 2022,
    description: "Website and booking platform for an indoor padel complex.",
    tags: ["Website", "UI/UX"],
    image: "/backgrounImage.png",
    featured: false,
    client: "Lucas Mora",
    date: "10 Apr 2025",
    services: ["Web Design", "Booking System", "UI / UX Design"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "market-wave",
    title: "Market Wave",
    category: "Marketing",
    year: 2022,
    description: "Digital marketing strategy and campaign visuals for a retail brand.",
    tags: ["Marketing", "Graphic Design"],
    image: "/topimage.jpg",
    featured: false,
    client: "Olivia Chen",
    date: "28 Feb 2025",
    services: ["Marketing", "Social Media", "Graphic Design"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "core-interface",
    title: "Core Interface",
    category: "Interface",
    year: 2022,
    description: "Product interface design for a B2B analytics platform.",
    tags: ["Interface", "UI/UX"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Ryan Park",
    date: "14 Jan 2025",
    services: ["Interface Design", "UI / UX Design", "Data Visualization"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
];

export const CATEGORIES = [
  "All works",
  "Branding",
  "Website",
  "Interface",
  "Graphic Design",
  "Application",
  "Marketing",
  "Logo & Identity",
  "Turnkey Website",
] as const;

export type Category = (typeof CATEGORIES)[number];

export function getWorkBySlug(slug: string): Work | undefined {
  return works.find((w) => w.slug === slug);
}

export function getFeaturedWorks(): Work[] {
  return works.filter((w) => w.featured);
}
