import type { Work } from "@/shared/types";

const LOREM =
  "Lorem ipsum dolor sit amet consectetur. Aenean ut magna justo libero risus neque at felis donec. Sit pulvinar cursus tempus ullamcorper facilisis elementum id velit convallis. Ac nulla suspendisse velit sit mattis vulputate aenean. Nunc in pretium in velit enim ut pulvinar dis. Est viverra mattis id sed neque erat vulputate duis.";

const twoParas = `${LOREM}\n\n${LOREM}`;

const gallery7 = (a: string, b: string, c: string): string[] => [a, b, c, a, b, c, a];

export const works: Work[] = [
  {
    slug: "mh-padel-club",
    title: "MH Padel Club",
    category: "Website",
    year: 2024,
    description: "Full-stack website for a padel sports club with booking system and brand identity.",
    tags: ["Web Design", "Full Stack Development", "Brand Design"],
    image: "/backgrounImage.png",
    featured: true,
    client: "MH Padel Club",
    date: "05 Mar 2026",
    projectUrl: "https://mhpadelclub.com",
    services: [
      "Logo Design",
      "Web Design",
      "UI / UX Design",
      "Marketing",
      "Full Stack Development",
      "Illustrations",
    ],
    blocks: [
      {
        type: "text",
        layout: "split",
        heading: "Context",
        paragraphs: [
          "MH Padel is a premium padel club and lifestyle brand based in Latvia, focused on combining sport, wellness, and community within a refined club environment. It positions itself not simply as a sports venue, but as a curated private-style destination where padel is presented through high standards of design, hospitality, and social culture. The brand emphasizes exclusivity, elegance, and disciplined club values, offering world-class courts, coaching, wellness amenities, and membership-based experiences.",
          "Padel is one of the fastest-growing sports globally, evolving from a niche activity into a contemporary social and lifestyle phenomenon. Its appeal lies in accessibility, energy, and the unique balance between competition and connection. As urban audiences increasingly seek experiences that combine sport, wellbeing, and community, premium padel clubs emerge as new cultural destinations rather than traditional sports facilities.",
          "Within this landscape, MH Padel positions itself as a refined environment where athletic performance meets elevated hospitality. The brand reflects a modern interpretation of club culture — disciplined, social, and aesthetically curated for a new generation of active audiences.",
        ],
      },
      {
        type: "wide",
        src: "/works/mh-padel-club/club-interior.jpg",
      },
      {
        type: "text",
        layout: "split",
        heading: "Concept",
        paragraphs: [
          "MH Padel is conceived as a modern club experience where sport becomes part of a broader lifestyle. The concept combines high-performance athletic culture with refined spatial aesthetics, hospitality, and social belonging. It is designed for people who value movement, discipline, and the quality of the environment around them.",
          "More than a sports destination, the brand creates a setting where padel functions as a social ritual — structured, elegant, and contemporary. Every element of the experience supports the idea of controlled energy, elevated standards, and a strong sense of community.",
        ],
      },
      {
        type: "text",
        layout: "split",
        heading: "Logo Description",
        paragraphs: [
          "The logo combines classical symbolism with contemporary minimalism, expressing the brand's premium club identity through a balanced and recognizable emblem. At the center, crossed padel rackets form the core visual element, directly representing the sport and emphasizing precision, discipline, and competitive spirit.",
          "The surrounding laurel wreath introduces references to achievement, heritage, and prestige, reinforcing the atmosphere of an elevated club culture. The monogram placed above functions as a distinctive brand signature, adding exclusivity and strengthening memorability.",
          "The composition is completed by the ball positioned at the base, creating visual balance and grounding the emblem in the world of sport. The restrained monochrome palette enhances elegance, clarity, and timeless character.",
        ],
      },
      {
        type: "wide",
        src: "/works/mh-padel-club/logo.jpg",
        fullWidth: true,
        objectFit: "contain",
        bg: "#000",
      },
      {
        type: "text",
        layout: "split",
        heading: "Typography & Colors",
        paragraphs: [
          "The visual language is built on the contrast between expressive typography and restrained color minimalism. Benzin ExtraBold serves as the primary display typeface, introducing strength, impact, and immediate recognizability. Its geometric weight gives the identity a confident and contemporary character, reinforcing the bold presence of the brand across headlines and key visual statements.",
          "Euclid Square Light complements the system as a secondary typeface, bringing clarity, balance, and sophistication. Its clean construction creates visual rhythm and supports readability in informational and supporting content. Together, the two typefaces establish a dialogue between power and refinement — reflecting both athletic energy and premium club aesthetics.",
          "The color palette is intentionally minimal: deep black (#000000) conveys discipline, focus, and exclusivity, while soft ivory (#E5DFCC) introduces warmth and understated elegance. This restrained contrast enhances timelessness and allows the brand to maintain a strong premium presence across physical and digital applications.",
        ],
      },
      {
        type: "wide",
        src: "/works/mh-padel-club/brand-identity.jpg",
        fullWidth: true,
        objectFit: "contain",
        bg: "#000",
      },
      {
        type: "text",
        layout: "split",
        heading: "Final Summary",
        paragraphs: [
          "Together, these visual elements form a coherent identity system that defines MH Padel as more than a sports brand. The combination of symbolic heritage, bold typography, and restrained color choices creates a visual language rooted in discipline, elegance, and contemporary club culture. Each component is designed to support a perception of quality, precision, and exclusivity while remaining clear and highly recognizable across different touchpoints.",
          "The identity reflects the broader idea behind MH Padel — a space where sport is experienced not only through performance, but also through atmosphere, social interaction, and aesthetic standards. The balance between strong graphic presence and minimal visual restraint allows the brand to communicate confidence without excess, creating a timeless character that can grow consistently across physical environments, digital platforms, and future brand extensions.",
          "As a result, the visual system positions MH Padel within a premium category where athletic energy, cultural relevance, and lifestyle value exist within one unified brand experience.",
        ],
      },
      {
        type: "gallery",
        columns: 2,
        images: [
          "/works/mh-padel-club/mockup-laptops.jpg",
          "/works/mh-padel-club/mockup-phone.jpg",
          "/works/mh-padel-club/mockup-laptop-pool.jpg",
          "/works/mh-padel-club/mockup-laptop-dark.jpg",
        ],
      },
      {
        type: "gallery",
        columns: 2,
        images: [
          "/works/mh-padel-club/mockup-devices.jpg",
          "/works/mh-padel-club/mockup-phones.jpg",
        ],
      },
      {
        type: "wide",
        src: "/works/mh-padel-club/closing.jpg",
        fullWidth: true,
        objectFit: "contain",
        bg: "#000",
      },
    ],
  },
  {
    slug: "mobi-scambank",
    title: "Mobi Scambank",
    category: "Marketing",
    year: 2024,
    description: "Marketing campaign and digital presence for a fintech startup.",
    tags: ["Marketing", "Branding"],
    image: "/topimage.jpg",
    featured: true,
    client: "Alex Carter",
    date: "12 Jan 2026",
    services: ["Branding", "Marketing", "Social Media", "Web Design"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/bottomimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "gpu-service",
    title: "GPU Service",
    category: "Turnkey Website",
    year: 2024,
    description: "Turnkey e-commerce website for a GPU repair and sales service.",
    tags: ["Website", "E-commerce"],
    image: "/bottomimage.jpg",
    featured: true,
    client: "Mike Stevens",
    date: "20 Feb 2026",
    services: ["Web Design", "E-commerce", "Full Stack Development"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/backgrounImage.png", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "interface-studio",
    title: "Interface Studio",
    category: "Interface",
    year: 2024,
    description: "Product design system for a SaaS startup with complex multi-role dashboard.",
    tags: ["Interface", "UI/UX", "Design System"],
    image: "/topimage.jpg",
    featured: true,
    client: "Daniel Frost",
    date: "18 Jan 2026",
    services: ["UI / UX Design", "Interface Design", "Design System", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "nova-brand",
    title: "Nova Brand",
    category: "Branding",
    year: 2024,
    description: "Brand identity and visual language for a luxury lifestyle label.",
    tags: ["Branding", "Logo & Identity"],
    image: "/bottomimage.jpg",
    featured: true,
    client: "Sara Bell",
    date: "02 Mar 2026",
    services: ["Logo Design", "Branding", "Visual Identity", "Typography"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "flow-app",
    title: "Flow App",
    category: "Application",
    year: 2024,
    description: "Mobile productivity app with focus on calm UX and habit tracking.",
    tags: ["Application", "Mobile", "UI/UX"],
    image: "/backgrounImage.png",
    featured: true,
    client: "Leo Grant",
    date: "25 Feb 2026",
    services: ["Mobile Design", "UI / UX Design", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "brand-identity-co",
    title: "Brand Identity Co.",
    category: "Branding",
    year: 2023,
    description: "Complete brand identity system for a design consultancy.",
    tags: ["Branding", "Logo & Identity"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Sophie Lane",
    date: "08 Nov 2025",
    services: ["Logo Design", "Branding", "Visual Identity", "Typography"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "interface-lab",
    title: "Interface Lab",
    category: "Interface",
    year: 2023,
    description: "UI/UX design for a SaaS dashboard with complex data visualisation.",
    tags: ["Interface", "UI/UX"],
    image: "/topimage.jpg",
    featured: false,
    client: "David Kim",
    date: "15 Oct 2025",
    services: ["UI / UX Design", "Interface Design", "Prototyping"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "sport-app",
    title: "Sport App",
    category: "Application",
    year: 2023,
    description: "Mobile application for sports event management and team coordination.",
    tags: ["Application", "Mobile"],
    image: "/backgrounImage.png",
    featured: false,
    client: "James Walker",
    date: "03 Sep 2025",
    services: ["Mobile Design", "UI / UX Design", "App Development"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "logo-studio",
    title: "Logo Studio",
    category: "Logo & Identity",
    year: 2023,
    description: "Logomark and identity system for a creative studio.",
    tags: ["Logo & Identity", "Branding"],
    image: "/topimage.jpg",
    featured: false,
    client: "Emma Ross",
    date: "22 Jul 2025",
    services: ["Logo Design", "Brand Identity", "Illustrations"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "graphic-press",
    title: "Graphic Press",
    category: "Graphic Design",
    year: 2023,
    description: "Editorial and print design for an independent magazine.",
    tags: ["Graphic Design", "Print"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Nina Black",
    date: "30 Jun 2025",
    services: ["Graphic Design", "Editorial Design", "Print"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/backgrounImage.png", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
  {
    slug: "turnkey-shop",
    title: "Turnkey Shop",
    category: "Turnkey Website",
    year: 2022,
    description: "Ready-to-launch e-commerce solution for a fashion retailer.",
    tags: ["Turnkey Website", "E-commerce"],
    image: "/backgrounImage.png",
    featured: false,
    client: "Chris Ford",
    date: "18 May 2025",
    services: ["Web Design", "E-commerce", "Full Stack Development"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/topimage.jpg", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "padel-arena",
    title: "Padel Arena",
    category: "Website",
    year: 2022,
    description: "Website and booking platform for an indoor padel complex.",
    tags: ["Website", "UI/UX"],
    image: "/backgrounImage.png",
    featured: false,
    client: "Lucas Mora",
    date: "10 Apr 2025",
    services: ["Web Design", "Booking System", "UI / UX Design"],
    about: twoParas,
    gallery: gallery7("/backgrounImage.png", "/bottomimage.jpg", "/topimage.jpg"),
    approach: twoParas,
    approachImage: "/backgrounImage.png",
  },
  {
    slug: "market-wave",
    title: "Market Wave",
    category: "Marketing",
    year: 2022,
    description: "Digital marketing strategy and campaign visuals for a retail brand.",
    tags: ["Marketing", "Graphic Design"],
    image: "/topimage.jpg",
    featured: false,
    client: "Olivia Chen",
    date: "28 Feb 2025",
    services: ["Marketing", "Social Media", "Graphic Design"],
    about: twoParas,
    gallery: gallery7("/topimage.jpg", "/backgrounImage.png", "/bottomimage.jpg"),
    approach: twoParas,
    approachImage: "/topimage.jpg",
  },
  {
    slug: "core-interface",
    title: "Core Interface",
    category: "Interface",
    year: 2022,
    description: "Product interface design for a B2B analytics platform.",
    tags: ["Interface", "UI/UX"],
    image: "/bottomimage.jpg",
    featured: false,
    client: "Ryan Park",
    date: "14 Jan 2025",
    services: ["Interface Design", "UI / UX Design", "Data Visualization"],
    about: twoParas,
    gallery: gallery7("/bottomimage.jpg", "/topimage.jpg", "/backgrounImage.png"),
    approach: twoParas,
    approachImage: "/bottomimage.jpg",
  },
];

export const CATEGORIES = [
  "All works",
  "Branding",
  "Website",
  "Interface",
  "Graphic Design",
  "Application",
  "Marketing",
  "Logo & Identity",
  "Turnkey Website",
] as const;

export type Category = (typeof CATEGORIES)[number];

export function getWorkBySlug(slug: string): Work | undefined {
  return works.find((w) => w.slug === slug);
}

export function getFeaturedWorks(): Work[] {
  return works.filter((w) => w.featured);
}
